### ISSUE TITLE
A lot of submissions in queue?

### ISSUE THREAD

**Issue by ryland-mortlock** [radio1988/OneStopRNAseq#16]
It seems like it is taking a while for jobs to go through right now, showing 24 jobs in queue
<img width="733" alt="image" src="https://github.com/user-attachments/assets/71318951-fc16-4d05-bf1c-fa8b7716974d">

Is there something wrong with the server or is it just a lot of people submitting jobs at the same time?
Thanks for any help you can provide.

**Comment by radio1988** [comment]
Hello, 

Sorry, we are implementing some updates and the website got stuck on a few jobs with wrong parameters selected.
- scRNASeq data used rather than bulk RNASeq data
- INTRON MODE and gDNA removal MODE selected at the same time

We are working on this problem and the queue should be moving next week.

**Comment by ryland-mortlock** [comment]
Hi, no problem. Thanks so much for letting me know.

Sincerely,
Ryland

**Comment by radio1988** [comment]
Hello Ryland,

The queue almost cleared. We accidentally set the job status to 'expired' because they are in the queue for too long. We will change the expiration time counting to job finished time to fix this issue. This might take one or two days.

Best,
Rui

**Comment by ryland-mortlock** [comment]
No worries, thanks for the update!

**Comment by radio1988** [comment]
the queue seem to be moving smoothly, let me close this issue
