### ISSUE TITLE
TE_ANALYSIS

### ISSUE THREAD

**Issue by ajg449** [radio1988/OneStopRNAseq#5]
Hello,

I didn't see this in the output description, but are separate output files created for DTE analysis using SalmonTE?

**Comment by radio1988** [comment]
Hello,

In OneStopRNASeq, currently, we only implemented the quantification of TEs using SalmonTE, i.e. the 'quant' mode.
The results are under SalmonTE_output/EXPR.csv. The rows are TEs, the columns are samples, the values are TPM.

The detailed description of SalmonTE quant output can be found here:
https://github.com/hyunhwan-jeong/SalmonTE

Best,
Rui (Ray)

**Comment by ajg449** [comment]
Hi Rui,

"SalmonTE_output/EXPR.csv" was not one of the outputs. I haven't seen it in previous runs with DTE analysis either. I wanted to check if the file was being exported properly.

**Comment by radio1988** [comment]
Hello,

For your 20220404_MM_progression_TE_analysis_10.37.56-04.04.2022 analysis_1
did you see SalmonTE_output?

Rui

**Comment by ajg449** [comment]
I didn't see that output. On the summary page, under DTE analysis, it says "Results are included in DGE results. Please note that this analysis is only available for human and mouse with input FASTQ or BAM files.". I couldn't find it in the DGE outputs from DEseq2. Is it located elsewhere?

**Comment by radio1988** [comment]
I see, you are actually asking a question about the output of TE_ANALYSIS, rather than SalmonTE.

In OneStopRNASeq website, the quantification of regular genes are performed with featureCount, the quantification of TEs are done with SalmonTE (quant mode). Then both count tables are merged together, creating an expression table containing both regular genes and TEs. This table is then analyzed by DESeq2, and the output is under DESeq2/ folder. 

If you look closely in all the output Excel files of DESeq2, e.g. TPM.xlsx, COUNT.xlsx, contrast_name.deseq2.xlsx, you can find TEs listed there as rows. 

However, now there is a bug on the backend that when you select 'INTRON' (gene level quantification) and 'TE_ANALYSIS' together, TE results are skipped.  We are working on fixing that now.

I see you submitted multiple jobs. Which submitted analysis would you like to have the corrected results?

Best,
Rui

**Comment by ajg449** [comment]
Ok, that's where I thought it would be located. I guess I ran into the bug because I selected for both exon and intron. Could you let me know when that issue is resolved?

I'd like to get corrected results for [20220404_MM_progression_TE_analysis_10.37.56-04.04.2022] and  [GSE109700_test_2_02.13.08-03.29.2022].

Thank you for all the assistance and for providing this platform. I really appreciate it.

**Comment by radio1988** [comment]
Our pleasure! 

New results can be downloaded for [20220404_MM_progression_TE_analysis_10.37.56-04.04.2022]  already, with TE included in DESeq2 results.


[GSE109700_test_2_02.13.08-03.29.2022] results should be updated in a few hours

Since we are planning on a major stable update to the website. We will update the website in a few weeks with a bunch of other stability issue fixed together. Submitting new jobs with both 'INTRON' and 'TE_ANALYSIS' together will still skip the TE analysis for now, but selecting 'TE_ANALYSIS' without 'INTRON' should be fine for now.

**Comment by radio1988** [comment]
Hello, 

Sorry to inform you that, for GSE109700_Proliferatingrep1, the GEO fastq files are not correct, with some issues. So the analysis has halted. We can't fix GEO's issue as it is out of the scope of our website

STAR.log:
ReadAlignChunk_processChunks.cpp:201:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or >

Fastqc Log:
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline '@SRR6515349.38029967 HWI-D00381:284:C62GEANXX:6:2103:16114:50919 length=125' didn't start with '+'
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:172)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
        at java.base/java.lang.Thread.run(Thread.java:834)

Rui

**Comment by ajg449** [comment]
Thank you for the new results. I was able to see the TEs in the results files this time around. And thanks for letting me know about the error with the fastq files from the GEO run.

For clarification on the previous issue with submitting jobs with "INTRON" and "TE_ANALYSIS", that means that selecting "EXON ONLY" should avoid the issue, correct?

On another note, I submitted another job with additional samples and without selecting "INTRON". It appears to be stuck, however. I wanted to see if it was still processing correctly or if the analysis halted. The job ID is 20220407_MM_progression_full_03.28.26-04.07.2022

**Comment by ajg449** [comment]
Hello again. Just following up on the previous comment. I cancelled the previous job 20220407_MM_progression_full_03.28.26-04.07.2022 and re-uploaded a new job 20220411_MM_progression_full_02.14.04-04.11.2022. Not sure if it is stuck or if it failed for some reason. Let me know if you think I should open this as its own separate issue. Thanks!

**Comment by radio1988** [comment]
With your new job, 22 of 161 steps (14%) done
Please be patient, with 277GB of fastq files being processed, it can take quite some time to get them aligned and processed.

With more users using the website, sometimes users are in queue waiting for their turns. 

Best,
Rui

**Comment by radio1988** [comment]
Selecting "TE_ANALYSIS"  without selecting "INTRON", should be working, let's see how it goes

**Comment by ajg449** [comment]
Hi, it looks like an error occurred when executing DESeq2.

Error executing rule DESeq2 on cluster (jobid: 72, external: Job <5008244> is submitted to queue <long>., jobscript: /project/umw_hira_goel/Kai/OneStopRNAseq/users/452/20220411_MM_progression_full_02.14.04-04.11.2022/analysis_1/.snakemake/tmp.m99_p_f5/snakejob.DESeq2.72.sh). For error details see the cluster log and the log files of the involved rule(s).

**Comment by radio1988** [comment]
Let me look into it

**Comment by radio1988** [comment]
Your DESeq2 results are mostly ready. Our server is having some technical issues. The html report is not generated, it should be fine later when the server is back online

**Comment by ajg449** [comment]
I wanted to follow up to see if the server issues were resolved and if it was back online.

**Comment by ajg449** [comment]
Hello. The last job appears to have expired without completing, so I resubmitted the job. It still appears to be failing to execute at the very end with the same error as before, so I figured there might still be some technical issues with the server. I just wanted to follow up again to see what the status was.

**Comment by radio1988** [comment]
Hello, 

Sorry about the delay. 

Problem solved. DESeq2 results all there.

I will close the topic now.

**Comment by radio1988** [comment]
So, your access to 20220411_MM_progression_full_02.14.04-04.11.2022 and 20220415_MM_progression_TE_analysis_04.08.04-04.15.2022 both expired? I saw you had a 20220419_MM_progression_05.54.17-04.19.2022 submitted. Are all three analysis the same?

**Comment by radio1988** [comment]
You should be able to see and download results in 20220415_MM_progression_TE_analysis_04.08.04-04.15.2022
We've deleted 20220411_MM_progression_full_02.14.04-04.11.2022 and 20220419_MM_progression_05.54.17-04.19.2022 since they are duplicates and takes extra space

If you have problem accessing DESeq2 results in 20220415_MM_progression_TE_analysis_04.08.04, please let me know

**Comment by ajg449** [comment]
I was able to download the results for 20220415_MM_progression_TE_analysis_04.08.04-04.15.2022 successfully. Thank you for checking with me. And apologies for the duplicate jobs. I didn't want to remove them until any troubleshooting had been completed, and was wondering if re-running after the server issue fix would work.

Thanks again for all the assistance and for providing this platform.

**Comment by radio1988** [comment]
Glad to hear that this issue has been solved.
